version: "3"
services:
  app:
    image: node:10-alpine
    command: npm run nodemon
    volumes:
      - .:/usr/ydb2/
    working_dir: /usr/ydb2/
    ports:
    - "8000:8000"
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"